<!DOCTYPE html>
<html lang="en-us">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>A subprocess bug? Nah.</title>
  <link href="http://philipson.co.il//css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="http://philipson.co.il//css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/styles/default.min.css">
  <style type="text/css">
  
    footer.page-footer{background-image: url(http://philipson.co.il//images/default.png);}
  
  </style>
</head>
<body>
  <ul id="slide-out" class="side-nav">
    <li><a href="http://philipson.co.il/"><i class="mdi-action-home left"></i>Home<i class="mdi-hardware-keyboard-arrow-right right"></i></a></li>
    <li><a href="http://philipson.co.il//categories"><i class="mdi-action-perm-media left"></i>Categories<i class="mdi-hardware-keyboard-arrow-right right"></i></a></li>
    <li><a href="http://philipson.co.il//tags"><i class="mdi-action-loyalty left"></i>Tags<i class="mdi-hardware-keyboard-arrow-right right"></i></a></li>
  </ul>
  <div id="index-banner" class="parallax-container">
  <a data-activates="slide-out" class="btn-floating button-collapse" style="top: 5px; left: 5px;"><i class="mdi-navigation-menu"></i></a>
    <div class="section no-pad-bot">
      <div class="container">
        
        <h1 class="header center teal-text text-lighten-2">Gavrie&#39;s Blog</h1>
        <div class="row center">
          <h5 class="header col s12 light">Musings on programming in Python and Go</h5>
        </div>
        <div class="row center">
        
          <a href="https://github.com/gavrie"><img src="http://philipson.co.il//images/github2-dreamstale35.png"></a>
        
        
        
          <a href="https://twitter.com/gavrieph"><img src="http://philipson.co.il//images/twitter-dreamstale71.png"></a>
        
        
        
          <a href="https://www.linkedin.com/in/gavrie"><img src="http://philipson.co.il//images/linkedin-dreamstale45.png"></a>
        
          <a href="http://philipson.co.il//index.xml"><img src="http://philipson.co.il//images/feed-dreamstale27.png"></a>
        </div>
      </div>
    </div>
    <div class="parallax">
    
      <img src="http://philipson.co.il//images/default.png">
    
    </div>
  </div>



<div class="container">
  <div class="section">

    <div class="row">
      <div class="col s12">
        <div class="card-panel">
          <h4>A subprocess bug? Nah.</h4>
          <p>
           
          </p>
          <p>

<p>A few weeks ago, a colleague came to me with an interesting bug: When running a child process with Python&rsquo;s <code>subprocess</code> module, no exception is thrown when the child process fails. In essence, what happened was the following (typed at the interactive Python prompt):</p>

<pre><code>&gt;&gt;&gt; import subprocess
&gt;&gt;&gt; subprocess.check_call(&quot;false&quot;)
0
</code></pre>

<p>The <code>false</code> command always exits with a nonzero exit code. The expected behavior, as confirmed on another machine, would be as follows:</p>

<pre><code>&gt;&gt;&gt; subprocess.check_call(&quot;false&quot;)
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py&quot;, line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'false' returned non-zero exit status 1
</code></pre>

<p>So, what happens is that <code>subprocess</code> thinks that the child process exited successfully, even though it did not.</p>

<p>This behavior, of course, wreaks total havoc with the application. Instead of an exception being thrown due to the failed child process, the application goes on and fails at a later point when it tries to do something based on the data received from the child process. This goes against the good design principle of <a href="http://en.wikipedia.org/wiki/Fail-fast">failing early</a>, as embodied by the way Python uses exceptions instead of error codes.</p>

<p>So, what is going on here? You may want to think it through and see if you can find the problem.</p>

<h2 id="diving-in:99cb9f24f3ea4237a647e70c92ab88eb">Diving In</h2>

<p>At first sight, this looks like a problem with either Python itself or with the OS (Linux, in our case). How could this happen?  The colleague who first encountered this issue looked at it through the Python debugger, and got as far as the <code>wait()</code> function of <code>subprocess</code>:</p>

<pre><code class="language-python">def wait(self):
    &quot;&quot;&quot;Wait for child process to terminate.  Returns returncode attribute.&quot;&quot;&quot;
    while self.returncode is None:
        try:
            pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
        except OSError as e:
            if e.errno != errno.ECHILD:
                raise
            # This happens if SIGCLD is set to be ignored or waiting
            # for child processes has otherwise been disabled for our
            # process.  This child is dead, we can't get the status.
            pid = self.pid
            sts = 0
        # Check the pid and loop as waitpid has been known to return
        # 0 even without WNOHANG in odd situations.  issue14396.
        if pid == self.pid:
            self._handle_exitstatus(sts)
    return self.returncode
</code></pre>

<p>As seen in the code, if <code>os.waitpid</code> on a child process fails with <code>ECHILD</code>, an exception is not raised. The reason for this is that <code>ECHILD</code> is returned in cases where there is no child process to be waited for. Normally, when a process terminates, the kernel keeps information such as its exit code until the parent calls <code>wait()</code> on it. In the interim, the process is a so-called &ldquo;zombie&rdquo;. If there is no child process (even not a zombie), we cannot know if it succeeded or failed.</p>

<p>The above piece of code went into Python&rsquo;s <code>subprocess</code> module as part of a fix for another problem, as documented in <a href="http://bugs.python.org/issue1731717">this Python bug report</a>.</p>

<p>Python chooses to assume that the child process exited successfully. Is this a correct assumption? Well, it&rsquo;s as good as any other. In the legitimate use case, namely when a process explicitly ignores <code>SIGCHLD</code> since it isn&rsquo;t interested in the exit code of its child processes, it makes sense for <code>waitpid()</code> to always complete successfully. Of course this can be argued against, but it is not a senseless assumption.</p>

<h2 id="back-to-the-code:99cb9f24f3ea4237a647e70c92ab88eb">Back to the Code</h2>

<p>Do we by any chance ignore <code>SIGCHLD</code> in our application? The chance we do is very small, since we run a lot of child processes and depend on their state all their time, and this fails only occasionally. A quick <code>git grep</code> on the code shows that we <em>do</em> ignore <code>SIGCHLD</code> in one specific standalone Python script, but that script is not part of the application and is run on a remote machine on which we indeed <em>should</em> ignore this signal.</p>

<p>At this point, I suspected (wrongly, as we shall see) that this was a problem with the specific host on which it happened, and resolved the issue as &ldquo;Can&rsquo;t reproduce&rdquo;. Since this happened more than once, this was not ideal, so I asked other team members to keep an eye open in case this happened again.</p>

<h2 id="a-week-later:99cb9f24f3ea4237a647e70c92ab88eb">A Week Later</h2>

<p>Of course, a week later it happened again. Fortunately, this time it was caught as it happened and we could look at the live process in the debugger. My colleague <a href="https://plus.google.com/107274679081446769903/">Erez Horev</a> called me over and we started looking at it together.</p>

<p>We easily reproduced the issue in the debugger. After a lot of dead ends, we concluded that the only logical way of this happening was indeed if the application ignored <code>SIGCHLD</code>. To check if this was the case, we ran the following in the debugger:</p>

<pre><code>&gt;&gt;&gt; signal.getsignal(signal.SIGCHLD)
1
&gt;&gt;&gt; signal.SIG_IGN
1
</code></pre>

<p>Indeed &ndash; <code>SIGCHLD</code> is being ignored by our application. How can this be? Nowhere in the code do we ignore <code>SIGCHLD</code>, except for that standalone script, which runs only on the remote machine. Or does it?</p>

<h2 id="checking-our-assumptions:99cb9f24f3ea4237a647e70c92ab88eb">Checking our Assumptions</h2>

<p>At this point, the only thing left to do was to look at that script. It includes the following line, right at the top.</p>

<pre><code class="language-python">signal.signal(signal.SIGCHLD, signal.SIG_IGN)
</code></pre>

<p>Could we, by any chance, have <code>imported</code> this script as a module in our application, therefore running the above code as a side effect?</p>

<p>It turns out we were doing exactly that. In recently added code, under specific circumstances, our application imports the module in order to get its filename and to deploy it to the remote machine. While normally <code>import</code> should be clean of side effects, the above <code>signal</code> code appears at the module level and not inside a function, and is therefore run when imported. This contaminates our application and causes it to ignore <code>SIGCHLD</code> with the described consequences.</p>

<p>Moving this line fixed the problem.</p>

<h2 id="question-everything:99cb9f24f3ea4237a647e70c92ab88eb">Question Everything</h2>

<p><a href="http://www.bignerdranch.com/about-us/nerds/mark-dalrymple.html">Mark Dalrymple</a>, in his <a href="http://www.bignerdranch.com/blog/thoughts-on-debugging-part-1/">Thoughts on Debugging, Part 1</a>, talks about the hierarchy of potential blame when debugging. In short, new code is the first suspect, after which come old code, library code etc. The point here is that the chance of there being a bug in Python is much smaller than that of there being a bug in your own code. Not only that, but the chance of the bug being in new code is the highest.</p>

<p>The idea of there being a bug in Python or an OS issue might have been valid, but it was not likely. The assumption that this <em>could not happen</em> since the relevant code does not run turned out to be false. The bug was indeed in our code, and in new code at that.</p>

<h2 id="conclusion:99cb9f24f3ea4237a647e70c92ab88eb">Conclusion</h2>

<p>As a lesson from this, aside from some debugging ideas, please remember: Don&rsquo;t run any code that may have side effects at the module top level! Somehow, some day, your module will be imported by other code that may be hurt by this side effect. Put all code in functions, or use the Python <code>if __name__ == '__main__'</code> construct.</p>
</p>
          <p>1 Jul 2014
            
              
                <a href="http://philipson.co.il//tags/python/">#python</a>
              
            
          </p>
          
            <div id="disqus_thread"></div>
<script type="text/javascript">
     
    var disqus_shortname = 'gavriesbl';
    
     
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
          
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col s3 m1">
      
        <a class="btn-floating btn-large waves-effect waves-light" href="http://philipson.co.il/post/goodbye-python-hello-go/"><i class="mdi-navigation-arrow-back"></i></a>
      
      </div>
      <div class="col s6 m10 center">&nbsp</div>
      <div class="col s3 m1">
      
        <a class="btn-floating btn-large waves-effect waves-light" href="http://philipson.co.il/post/buffers-will-fill-up-eventually/"><i class="mdi-navigation-arrow-forward"></i></a>
      
      </div>
    </div>

  </div>
</div>

  <footer class="page-footer">
    <div class="footer-copyright">
      <div class="container">
      © 2016 by Gavrie Philipson
      <div class="right">Design <a class="grey-text text-lighten-4" href="http://pdevty.github.io/blog/">pdevty</a></div>
      </div>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="http://philipson.co.il//js/materialize.min.js"></script>
  <script src="http://philipson.co.il//js/init.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  

  </body>
</html>

